"""
Django settings for netdelta project.

Generated by 'django-admin startproject' using Django 1.9.7.

For more information on this file, see
https://docs.djangoproject.com/en/1.9/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.9/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.9/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '8zz3_f_e0oi7#6=sl$ek=7p$-$ao(s1llo@1_jz1wldh4#lp$)'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ADMINS = [('admin', 'ian.tibble@netdelta.io')]

SITE_NAME = "SITENAME"

# Application definition

INSTALLED_APPS = [
    'django_celery_results',
    'django_celery_beat',
    'nd',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'netdelta.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR + '/templates',
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'netdelta.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.9/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql', # Add 'postgresql_psycopg2', 'mysql', 'sqlite3' or 'oracle'.
        'NAME': 'netdelta_SITENAME',                  # Not used with sqlite3.
        'USER': 'root',                      # Not used with sqlite3.
        'PASSWORD': 'ankSQL4r4',
        'OPTIONS': dict(init_command="SET sql_mode='STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER'"),
    }
}


# Password validation
# https://docs.djangoproject.com/en/1.9/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.9/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.9/howto/static-files/

STATIC_URL = '/static/'

# Absolute path to the directory static files should be collected to.
# Don't put anything in this directory yourself; store your static files
# in apps' "static/" subdirectories and in STATICFILES_DIRS.
# Example: "/home/media/media.lawrence.com/static/"
STATIC_ROOT = BASE_DIR + '/netdelta/admin'

# Additional locations of static files
STATICFILES_DIRS = (
    # Put strings here, like "/home/html/static" or "C:/www/django/static".
    # Always use forward slashes, even on Windows.
    # Don't forget to use absolute paths, not relative paths.
    BASE_DIR + '/netdelta',
)

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.7/howto/static-files/

STATICFILES_FINDERS = (
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
)

LOGIN_URL='/admin/'
LOGIN_REDIRECT_URL='/scan/'

CELERY_DEFAULT_QUEUE = 'SITENAME'
CELERY_RESULT_BACKEND = 'django-db'
CELERY_IMPORTS = ("nd.tasks", )
CELERY_ENABLE_UTC = True
#CELERY_TIME_ZONE = 'GMT+0'
CELERY_ACCEPT_CONTENT = ['pickle', 'json', 'msgpack', 'yaml']
BROKER_URL = 'amqp://localhost:5672//'
# where to store periodic tasks (needed for scheduler)
CELERYBEAT_SCHEDULER = "django_celery_beat.schedulers.DatabaseScheduler"

#CELERY_BEAT_SCHEDULE = {}
SESSION_SERIALIZER = 'django.contrib.sessions.serializers.PickleSerializer'

CELERY_QUEUES = {"SITENAME": {"exchange": "SITENAME",
                              "routing_key": "SITENAME"}}

CELERY_ROUTES = {
    'nd.tasks.scheduled_scan': {'queue': "SITENAME",
                                'exchange': "SITENAME",
                                'routing_key': "SITENAME"},
}

ALLOWED_HOSTS = ['newvm', 'localhost', 'SITENAME.netdelta.io', '127.0.0.1']


# Mail server settings
ALERTS_TEST_TIMEOUT = 40   #timeout time in seconds
ALERTS_MAIL_SERVER = 'localhost'
#SMTP_USER_NAME = 'netdelta@netdelta.io'
SMTP_USER_NAME = ''
#SMTP_PASSWORD = 'octl1912'
USE_SSL = 'False'
SMTP_PORT = '25'
ALERTS_SENDER = 'netdelta@netdelta.io'
ALERTS_SUBJECT = 'NetDelta Found'
ALERT_ON_UNRESPONSIVE = 'True'
ALERT_ON_REMOVED_SERVICE = 'True'

IGNORE_TCPWRAPPED = False

IGNORE_SERVICE_SCAN_TIMEOUTS = 'True'

UNRESPONSIVE_HOSTS_DISPLAY_THRESHOLD = 10

LICENSE_TARGETS_LIMIT = 512

DELTA_HISTORY_WINDOW = 35 # < 3 = disable this setting
HIDE_REPEAT_DELTAS = False
